
# tap repositories and their packages

tap homebrew/core
brew abseil
brew ada-url
brew adns
brew ansible
brew ant
brew anyenv
brew aom
brew apache-serf
brew apr
brew apr-util
brew aribb24
brew asdf
brew autoconf
brew automake
brew aws-c-auth
brew aws-c-cal
brew aws-c-common
brew aws-c-compression
brew aws-c-event-stream
brew aws-c-http
brew aws-c-io
brew aws-c-mqtt
brew aws-c-s3
brew aws-c-sdkutils
brew aws-checksums
brew aws-elasticbeanstalk
brew aws-iam-authenticator
brew awscli
brew axel
brew bash
brew bash-completion
brew bazel
brew bdw-gc
brew berkeley-db
brew berkeley-db@5
brew bitwarden-cli
brew boost
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew cask
brew cffi
brew chrome-cli
brew circleci
brew cjson
brew cmake
brew cmocka
brew colordiff
brew coreutils
brew d2
brew dav1d
brew direnv
brew docbook
brew docbook-xsl
brew duti
brew dyff
brew eksctl
brew emacs
brew exiftool
brew expat
brew eza
brew ffmpeg
brew flac
brew fmt
brew fontconfig
brew fontforge
brew freetype
brew frei0r
brew fribidi
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gflags
brew gh
brew ghostscript
brew giflib
brew git
brew git-flow
brew git-lfs
brew glasskube
brew glib
brew glow
brew gmp
brew gnu-getopt
brew gnupg
brew gnutls
brew go
brew gobject-introspection
brew golangci-lint
brew gpgme
brew gradle
brew gradle-completion
brew graphite2
brew graphviz
brew grep
brew grpc
brew gts
brew guile
brew hadoop
brew handbrake
brew harfbuzz
brew hdrhistogram_c
brew helm
brew helm@3
brew helmfile
brew highway
brew hub
brew icu4c
brew icu4c@76
brew icu4c@77
brew imagemagick
brew imath
brew iproute2mac
brew isl
brew istioctl
brew ivy
brew jansson
brew jasper
brew jbig2dec
brew jemalloc
brew jmeter
brew jpeg
brew jpeg-turbo
brew jpeg-xl
brew jq
brew json-c
brew k9s
brew kompose
brew krew
brew kube-ps1
brew kubectx
brew kubernetes-cli
brew kustomize
brew lame
brew leptonica
brew libarchive
brew libass
brew libassuan
brew libavif
brew libb2
brew libbluray
brew libcbor
brew libdatrie
brew libde265
brew libdeflate
brew libdvdcss
brew libdvdnav
brew libdvdread
brew libev
brew libevent
brew libffi
brew libfido2
brew libgcrypt
brew libgit2
brew libgit2@1.7
brew libgit2@1.8
brew libgpg-error
brew libheif
brew libidn
brew libidn2
brew libksba
brew liblqr
brew libmicrohttpd
brew libmpc
brew libnghttp2
brew libnghttp3
brew libngtcp2
brew libogg
brew libomp
brew libpng
brew libpthread-stubs
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libspiro
brew libssh
brew libssh2
brew libtasn1
brew libtermkey
brew libthai
brew libtiff
brew libtomcrypt
brew libtommath
brew libtool
brew libudfread
brew libultrahdr
brew libunibreak
brew libuninameslist
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew libzip
brew little-cms2
brew llhttp
brew lpeg
brew lua
brew luajit
brew luajit-openresty
brew luv
brew lz4
brew lzo
brew m4
brew make
brew makedepend
brew mas
brew maven
brew mbedtls
brew mbedtls@3
brew mercurial
brew merve
brew mongodb-atlas-cli
brew mongosh
brew mpdecimal
brew mpfr
brew mpg123
brew msgpack
brew mysql
brew mysql@8.0
brew nasm
brew nbytes
brew ncurses
brew neovim
brew netcat
brew netpbm
brew nettle
brew nghttp2
brew node
brew node-build
brew npth
brew oniguruma
brew openblas
brew opencore-amr
brew openexr
brew openjdk
brew openjdk@11
brew openjdk@17
brew openjdk@21
brew openjpeg
brew openjph
brew openssl@3
brew openssl@4
brew operator-sdk
brew opus
brew p11-kit
brew p7zip
brew pango
brew parallel
brew pcre
brew pcre2
brew perl
brew pinentry
brew pixman
brew pkg-config
brew powerline-go
brew protobuf
brew protobuf@29
brew protobuf@33
brew pycparser
brew python
brew python-certifi
brew python-cryptography
brew python-packaging
brew python@3.10
brew python@3.11
brew python@3.12
brew python@3.9
brew r
brew rav1e
brew re2
brew readline
brew reattach-to-user-namespace
brew redis
brew remarshal
brew rename
brew ripgrep
brew rtmpdump
brew rubberband
brew ruby
brew ruby-build
brew s2n
brew scons
brew sdl2
brew sdl3
brew shared-mime-info
brew sheldon
brew shfmt
brew simdjson
brew simdutf
brew sipcalc
brew skinny
brew skopeo
brew snappy
brew speex
brew sphinx-doc
brew sqlite
brew squid
brew srt
brew stern
brew stoken
brew subversion
brew svt-av1
brew tcl-tk
brew tcl-tk@8
brew terragrunt
brew tesseract
brew texi2html
brew tfenv
brew theora
brew tmux
brew trash
brew tree
brew tree-sitter
brew tree-sitter@0.25
brew unbound
brew unibilium
brew utf8proc
brew util-macros
brew uvwasi
brew vim
brew watch
brew webp
brew wget
brew wireguard-go
brew wireguard-tools
brew woff2
brew x264
brew x265
brew xmlto
brew xorgproto
brew xvid
brew xz
brew yamllint
brew yq
brew zeromq
brew zimg
brew zlib-ng-compat
brew zookeeper
brew zsh
brew zsh-autosuggestions
brew zsh-completions
brew zsh-git-prompt
brew zsh-history-substring-search
brew zsh-lovers
brew zsh-navigation-tools
brew zsh-syntax-highlighting
brew zstd

tap homebrew/cask
cask alfred
cask brave-browser
cask chatgpt
cask choosy
cask claude
cask claude-code
cask coderunner
cask codex
cask copilot-cli
cask dbeaver-community
cask deepl
cask discord
cask docker
cask fantastical
cask font-hack-nerd-font
cask font-ricty-diminished
cask google-chrome
cask google-cloud-sdk
cask google-drive
cask google-gemini
cask google-japanese-ime
cask istat-menus
cask iterm2
cask lasso-app
cask macfuse
cask markedit
cask microsoft-auto-update
cask monitorcontrol
cask mysqlworkbench
cask ngrok
cask nordvpn
cask notunes
cask pdf-expert
cask pdfelement
cask slack
cask sourcetree
cask the-unarchiver
cask visual-studio-code
cask vlc
cask zoom

tap argon/mas

tap buo/cask-upgrade

tap daipeihust/tap

tap derailed/k9s

tap dtan4/dtan4

tap dtan4/tools

tap garethr/kubeval

tap glasskube/tap

tap grpc/grpc

tap hashicorp/tap

tap homeport/tap

tap instrumenta/instrumenta

tap okteto/cli

tap rcmdnk/file
brew brew-file

tap robscott/tap

tap rs/tap

tap sanemat/font

tap vectordotdev/brew

tap weaveworks/tap

# Other Homebrew packages
brew libcroco

# App Store applications
appstore 1352778147 Bitwarden (2026.8.0)
appstore 640199958 Developer (11.0.2)
appstore 1380563956 Dictionaries (1.4.6)
appstore 549083868 Display Menu (2.2.6)
appstore 1452453066 Hidden Bar (1.8)
appstore 361285480 Keynote Creator Studio (15.3.1)
appstore 539883307 LINE (26.4.2)
appstore 361304891 Numbers Creator Studio (15.3.1)
appstore 361309726 Pages Creator Studio (15.3.1)
appstore 1451685025 WireGuard (1.0.16)
appstore 497799835 Xcode (26.6)
